language: python
sudo: false
notifications:
    email: change

python:
    - 3.5
    - 3.6

env:
    - LINTING=1
    - DOCTEST=1

matrix:
    include:
    - python: 3.6
      env:
        - COVERAGE=1
    - python: 3.7
      dist: xenial
      sudo: required

before_install:
    - python -m pip install --upgrade pip
    - if [ "${LINTING}" == "1" ]; then
          pip install flake8;
      fi
    - if [ "${COVERAGE}" == "1" ]; then
          pip install coverage coveralls codecov pytest pytest-cov;
      fi

install:
    - if [ "${DOCTEST}" == "1" ]; then
          pip install -e .[doc];
      else
          pip install -e .;
      fi

script:
    - |
      if [ "${LINTING}" == "1" ]; then
          flake8 ppmi;
      elif [ "${DOCTEST}" == "1" ]; then
          cd docs;
          make html;
          make doctest;
      else
          if [ "${COVERAGE}" == "1" ]; then
              TEST_ARGS="--cov-report term-missing --cov=ppmi";
          fi
          py.test ${TEST_ARGS} ppmi;
      fi

after_success:
    - if [ "${COVERAGE}" == "1" ]; then
          coveralls; codecov;
      fi
